// const colors = {
//   white: "#d9dae2",
//   gray: "#63676b",
//   darkblack: "#141A25",
//   black: "#12151b",
//   pink: "#da70d6",
//   red: "#f14c4c",
//   orange: "#ee8f73",
//   yellow: "#f8d701",
//   green: "#5fca83",
//   darkgreen: "#5cb4b4",
//   cyan: "#61dafb",
//   sky: "#4fc3fc",
//   blue: "#548ec5",
//   purple: "#8777e2",
// };

// export const {
//   white,
//   gray,
//   darkblack,
//   black,
//   pink,
//   red,
//   orange,
//   yellow,
//   green,
//   darkgreen,
//   cyan,
//   sky,
//   blue,
//   purple,
// } = colors;
